"""initial migration

Revision ID: 60e0d1a9a1e2
Revises: 
Create Date: 2025-11-11 22:34:20.805380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e0d1a9a1e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('draw_type', sa.String(length=50), nullable=False),
    sa.Column('draw_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('require_address', sa.Boolean(), nullable=True),
    sa.Column('require_phone', sa.Boolean(), nullable=True),
    sa.Column('invite_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_creator_id'), 'draws', ['creator_id'], unique=False)
    op.create_index(op.f('ix_draws_id'), 'draws', ['id'], unique=False)
    op.create_index(op.f('ix_draws_invite_code'), 'draws', ['invite_code'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_draw_id'), 'participants', ['draw_id'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('draw_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('giver_participant_id', sa.Integer(), nullable=False),
    sa.Column('receiver_participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giver_participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_id', 'giver_participant_id', name='uq_draw_giver')
    )
    op.create_index(op.f('ix_draw_results_draw_id'), 'draw_results', ['draw_id'], unique=False)
    op.create_index(op.f('ix_draw_results_giver_participant_id'), 'draw_results', ['giver_participant_id'], unique=False)
    op.create_index(op.f('ix_draw_results_id'), 'draw_results', ['id'], unique=False)
    op.create_index(op.f('ix_draw_results_receiver_participant_id'), 'draw_results', ['receiver_participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draw_results_receiver_participant_id'), table_name='draw_results')
    op.drop_index(op.f('ix_draw_results_id'), table_name='draw_results')
    op.drop_index(op.f('ix_draw_results_giver_participant_id'), table_name='draw_results')
    op.drop_index(op.f('ix_draw_results_draw_id'), table_name='draw_results')
    op.drop_table('draw_results')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_draw_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_draws_invite_code'), table_name='draws')
    op.drop_index(op.f('ix_draws_id'), table_name='draws')
    op.drop_index(op.f('ix_draws_creator_id'), table_name='draws')
    op.drop_table('draws')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
